#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Akito Hamano
# SPDX-License-Identifier: BSD-3-Clause

import sys

xlist = list(map(float, sys.stdin.readline().strip().split()))
ylist = list(map(float, sys.stdin.readline().strip().split()))
tmp1 = 0
tmp2 = 0
xylist = []
xsquare = []

for i in range(len(xlist)):
    tmp1 = xlist[i] * ylist[i]
    xylist.append(tmp1)

for n in range(len(xlist)):
    tmp2 = xlist[n] * xlist[n]
    xsquare.append(tmp2)

#計算
xave = sum(xlist) / len(xlist) #xの平均
yave = sum(ylist) / len(ylist) #yの平均
xyave = sum(xylist) / len(xylist) #xyの平均
xsave = sum(xsquare) / len(xsquare) #xの二乗の平均
xaves = pow(xave,2) #xの平均の二乗

#それぞれの値を小数部を二桁に丸める
rxave = round(xave,2)
ryave = round(yave,2)
rxyave = round(xyave,2)
rxsave = round(xsave,2)
rxaves = round(xaves,2)

a = (rxyave - (rxave * ryave)) / (rxsave - rxaves)
b = ((-1) * (round(a,2) * rxave)) + ryave

print("xの平均:", rxave, "   yの平均:", ryave, "   x*yの平均:", rxyave, "   xの二乗の平均:", rxsave, "   xの平均の二乗:", rxaves, sep='')
