#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Akito Hamano
# SPDX-License-Identifier: BSD-3-Clause

import sys

#リストの読み込み
xlist = list(map(float, sys.stdin.readline().strip().split()))
ylist = list(map(float, sys.stdin.readline().strip().split()))
tmp1 = 0
tmp2 = 0
xylist = []
xsquare = []

#使用するリストの計算
#x*yのリスト
for i in range(len(xlist)):
    tmp1 = xlist[i] * ylist[i]
    xylist.append(tmp1)

#xの二乗のリスト
for n in range(len(xlist)):
    tmp2 = xlist[n] * xlist[n]
    xsquare.append(tmp2)

#計算
xave = sum(xlist) / len(xlist) #xの平均
yave = sum(ylist) / len(ylist) #yの平均
xyave = sum(xylist) / len(xylist) #xyの平均
xsave = sum(xsquare) / len(xsquare) #xの二乗の平均
xaves = pow(xave,2) #xの平均の二乗

#それぞれの値を小数部を二桁に丸める
rxave = round(xave,2)
ryave = round(yave,2)
rxyave = round(xyave,2)
rxsave = round(xsave,2)
rxaves = round(xaves,2)

#最小二乗法の傾き
a = (rxyave - (rxave * ryave)) / (rxsave - rxaves)
#最小二乗法の切片
b = ((-1) * (round(a,2) * rxave)) + ryave

print("xの平均:", rxave)
print("yの平均:", ryave)
print("x*yの平均:", rxyave)
print("xの二乗の平均:", rxsave)
print("xの平均の二乗:", rxaves)
print("最小二乗法の式は: y = ", a, "x + ", b, sep='')
