#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Akito Hamano <s23c1112pf@s.chibakoudai.jp>

import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
        

